// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestVotesRequest struct {
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	RaftServerId         int32    `protobuf:"varint,2,opt,name=RaftServerId,proto3" json:"RaftServerId,omitempty"`
	LastLogIndex         int32    `protobuf:"varint,3,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          int32    `protobuf:"varint,4,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVotesRequest) Reset()         { *m = RequestVotesRequest{} }
func (m *RequestVotesRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVotesRequest) ProtoMessage()    {}
func (*RequestVotesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *RequestVotesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVotesRequest.Unmarshal(m, b)
}
func (m *RequestVotesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVotesRequest.Marshal(b, m, deterministic)
}
func (m *RequestVotesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVotesRequest.Merge(m, src)
}
func (m *RequestVotesRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVotesRequest.Size(m)
}
func (m *RequestVotesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVotesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVotesRequest proto.InternalMessageInfo

func (m *RequestVotesRequest) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVotesRequest) GetRaftServerId() int32 {
	if m != nil {
		return m.RaftServerId
	}
	return 0
}

func (m *RequestVotesRequest) GetLastLogIndex() int32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVotesRequest) GetLastLogTerm() int32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVotesResponse struct {
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=VoteGranted,proto3" json:"VoteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVotesResponse) Reset()         { *m = RequestVotesResponse{} }
func (m *RequestVotesResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVotesResponse) ProtoMessage()    {}
func (*RequestVotesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *RequestVotesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVotesResponse.Unmarshal(m, b)
}
func (m *RequestVotesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVotesResponse.Marshal(b, m, deterministic)
}
func (m *RequestVotesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVotesResponse.Merge(m, src)
}
func (m *RequestVotesResponse) XXX_Size() int {
	return xxx_messageInfo_RequestVotesResponse.Size(m)
}
func (m *RequestVotesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVotesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVotesResponse proto.InternalMessageInfo

func (m *RequestVotesResponse) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVotesResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type AppendEntriesRequest struct {
	Term                 int32            `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderId             int32            `protobuf:"varint,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	PrevLogIndex         int32            `protobuf:"varint,3,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          int32            `protobuf:"varint,4,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	LeaderCommitIndex    int32            `protobuf:"varint,6,opt,name=LeaderCommitIndex,proto3" json:"LeaderCommitIndex,omitempty"`
	Entries              map[int32]string `protobuf:"bytes,7,rep,name=Entries,proto3" json:"Entries,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(m, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() int32 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogIndex() int32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() int32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderCommitIndex() int32 {
	if m != nil {
		return m.LeaderCommitIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() map[int32]string {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(m, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*RequestVotesRequest)(nil), "rpc.RequestVotesRequest")
	proto.RegisterType((*RequestVotesResponse)(nil), "rpc.RequestVotesResponse")
	proto.RegisterType((*AppendEntriesRequest)(nil), "rpc.AppendEntriesRequest")
	proto.RegisterMapType((map[int32]string)(nil), "rpc.AppendEntriesRequest.EntriesEntry")
	proto.RegisterType((*AppendEntriesResponse)(nil), "rpc.AppendEntriesResponse")
}

func init() {
	proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b)
}

var fileDescriptor_b042552c306ae59b = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x94, 0x2f, 0x07, 0x4c, 0x74, 0xc4, 0xa4, 0xf4, 0xd4, 0xf4, 0x60, 0x38, 0x98, 0x1e,
	0xf0, 0x62, 0x38, 0x69, 0x0c, 0x51, 0x92, 0x1e, 0x4c, 0x31, 0xde, 0x6b, 0x3b, 0x18, 0xa2, 0xb4,
	0x75, 0x77, 0x21, 0xf2, 0x3b, 0x3c, 0xf8, 0x57, 0xfc, 0x79, 0x66, 0xb7, 0x8b, 0x59, 0xb0, 0x72,
	0xea, 0xbe, 0x37, 0xaf, 0x33, 0xef, 0x75, 0xb6, 0x00, 0x2c, 0x9e, 0x89, 0xa0, 0x60, 0xb9, 0xc8,
	0xd1, 0x66, 0x45, 0xe2, 0x7f, 0x5a, 0x70, 0x1a, 0xd1, 0xfb, 0x92, 0xb8, 0x78, 0xca, 0x05, 0x71,
	0x7d, 0x46, 0x84, 0xfa, 0x23, 0xb1, 0x85, 0x63, 0x79, 0xd6, 0xa0, 0x11, 0xa9, 0x33, 0xfa, 0xd0,
	0x8d, 0xe2, 0x99, 0x98, 0x12, 0x5b, 0x11, 0x9b, 0xa4, 0x4e, 0x4d, 0xd5, 0xb6, 0x38, 0xa9, 0x09,
	0x63, 0x2e, 0xc2, 0xfc, 0x65, 0x92, 0xa5, 0xf4, 0xe1, 0xd8, 0xa5, 0xc6, 0xe4, 0xd0, 0x83, 0x8e,
	0xc6, 0x6a, 0x44, 0x5d, 0x49, 0x4c, 0xca, 0x0f, 0xa1, 0xb7, 0x6d, 0x8a, 0x17, 0x79, 0xc6, 0xa9,
	0xd2, 0x95, 0x07, 0x1d, 0x29, 0xba, 0x63, 0x71, 0x26, 0xa8, 0x34, 0xd5, 0x8e, 0x4c, 0xca, 0xff,
	0xae, 0x41, 0xef, 0xa6, 0x28, 0x28, 0x4b, 0xc7, 0x99, 0x60, 0xf3, 0xfd, 0x21, 0x5d, 0x68, 0x87,
	0x14, 0xa7, 0x46, 0xc0, 0x5f, 0x2c, 0xc3, 0x3d, 0x30, 0x5a, 0xed, 0x86, 0x33, 0x39, 0x69, 0x47,
	0x63, 0x33, 0x9c, 0x41, 0xe1, 0x05, 0x9c, 0x94, 0x1d, 0x6f, 0xf3, 0xc5, 0x62, 0x2e, 0xca, 0x56,
	0x4d, 0xa5, 0xfb, 0x5b, 0xc0, 0x6b, 0x68, 0x69, 0xd7, 0x4e, 0xcb, 0xb3, 0x07, 0x9d, 0xe1, 0x79,
	0xc0, 0x8a, 0x24, 0xa8, 0xca, 0x13, 0x68, 0x28, 0x1f, 0xeb, 0x68, 0xf3, 0x9a, 0x3b, 0x82, 0xae,
	0x59, 0xc0, 0x63, 0xb0, 0x5f, 0x69, 0xad, 0x43, 0xcb, 0x23, 0xf6, 0xa0, 0xb1, 0x8a, 0xdf, 0x96,
	0xa4, 0x02, 0x1f, 0x46, 0x25, 0x18, 0xd5, 0xae, 0x2c, 0x7f, 0x0c, 0x67, 0x3b, 0x93, 0xf6, 0x6c,
	0xc2, 0x81, 0xd6, 0x74, 0x99, 0x24, 0xc4, 0xb9, 0xde, 0xc2, 0x06, 0x0e, 0xbf, 0x2c, 0xa8, 0xcb,
	0x6b, 0x82, 0x63, 0xe8, 0x9a, 0x8b, 0x45, 0x47, 0x85, 0xa9, 0xb8, 0x80, 0x6e, 0xbf, 0xa2, 0x52,
	0xce, 0xf6, 0x0f, 0xf0, 0x1e, 0x8e, 0xb6, 0x6c, 0x61, 0xff, 0xdf, 0x8f, 0xe2, 0xba, 0x55, 0xa5,
	0x4d, 0xa7, 0xe7, 0xa6, 0xfa, 0x17, 0x2e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x23, 0xe3, 0xda,
	0xab, 0x19, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	RequestVotes(ctx context.Context, in *RequestVotesRequest, opts ...grpc.CallOption) (*RequestVotesResponse, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) RequestVotes(ctx context.Context, in *RequestVotesRequest, opts ...grpc.CallOption) (*RequestVotesResponse, error) {
	out := new(RequestVotesResponse)
	err := c.cc.Invoke(ctx, "/rpc.Raft/RequestVotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, "/rpc.Raft/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	RequestVotes(context.Context, *RequestVotesRequest) (*RequestVotesResponse, error)
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
}

// UnimplementedRaftServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (*UnimplementedRaftServer) RequestVotes(ctx context.Context, req *RequestVotesRequest) (*RequestVotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVotes not implemented")
}
func (*UnimplementedRaftServer) AppendEntries(ctx context.Context, req *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_RequestVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Raft/RequestVotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVotes(ctx, req.(*RequestVotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVotes",
			Handler:    _Raft_RequestVotes_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
