// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddEntryRequest struct {
	Key                  int32    `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEntryRequest) Reset()         { *m = AddEntryRequest{} }
func (m *AddEntryRequest) String() string { return proto.CompactTextString(m) }
func (*AddEntryRequest) ProtoMessage()    {}
func (*AddEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *AddEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEntryRequest.Unmarshal(m, b)
}
func (m *AddEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEntryRequest.Marshal(b, m, deterministic)
}
func (m *AddEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEntryRequest.Merge(m, src)
}
func (m *AddEntryRequest) XXX_Size() int {
	return xxx_messageInfo_AddEntryRequest.Size(m)
}
func (m *AddEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEntryRequest proto.InternalMessageInfo

func (m *AddEntryRequest) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *AddEntryRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AddEntryResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEntryResponse) Reset()         { *m = AddEntryResponse{} }
func (m *AddEntryResponse) String() string { return proto.CompactTextString(m) }
func (*AddEntryResponse) ProtoMessage()    {}
func (*AddEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *AddEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEntryResponse.Unmarshal(m, b)
}
func (m *AddEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEntryResponse.Marshal(b, m, deterministic)
}
func (m *AddEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEntryResponse.Merge(m, src)
}
func (m *AddEntryResponse) XXX_Size() int {
	return xxx_messageInfo_AddEntryResponse.Size(m)
}
func (m *AddEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddEntryResponse proto.InternalMessageInfo

func (m *AddEntryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*AddEntryRequest)(nil), "api.AddEntryRequest")
	proto.RegisterType((*AddEntryResponse)(nil), "api.AddEntryResponse")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xb2, 0xe4, 0xe2, 0x77, 0x4c,
	0x49, 0x71, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0,
	0x62, 0xf6, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0x85, 0x44, 0xb8,
	0x58, 0xc3, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x25,
	0x1d, 0x2e, 0x01, 0x84, 0xd6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xe0,
	0xd2, 0xe4, 0xe4, 0xd4, 0xe2, 0x62, 0xb0, 0x7e, 0x8e, 0x20, 0x18, 0xd7, 0xc8, 0x81, 0x8b, 0xd9,
	0xb1, 0x20, 0x53, 0xc8, 0x92, 0x8b, 0x03, 0xa6, 0x49, 0x48, 0x44, 0x0f, 0xe4, 0x18, 0x34, 0xeb,
	0xa5, 0x44, 0xd1, 0x44, 0x21, 0x26, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x9d, 0x6d, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x25, 0x61, 0xc3, 0xa3, 0xc3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	AddEntry(ctx context.Context, in *AddEntryRequest, opts ...grpc.CallOption) (*AddEntryResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) AddEntry(ctx context.Context, in *AddEntryRequest, opts ...grpc.CallOption) (*AddEntryResponse, error) {
	out := new(AddEntryResponse)
	err := c.cc.Invoke(ctx, "/api.Api/AddEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	AddEntry(context.Context, *AddEntryRequest) (*AddEntryResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) AddEntry(ctx context.Context, req *AddEntryRequest) (*AddEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEntry not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_AddEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AddEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/AddEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AddEntry(ctx, req.(*AddEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEntry",
			Handler:    _Api_AddEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
